Feature/fafp1 19 product description page
AntonSadovnik/final-project-shop pull request #10
Opened 2022-08-15 17:05 UTC by LarisaDoroshchuk

2022-08-15 19:56 UTC, AntonSadovnik requested changes
1. Все иконки, что ты скачивала лучше сделать иконками через материал юай, у меня в json файле есть зависимость, просто установи себе на локалку и загугли material ui icons, если нужен пример как с ними работать смотри доку и мой компонент Activities.jsx что в Header находится
2. Попробуй стили записывать инлайново в сам компонент, если они не повторяются несколько к ряду или это не ховеры с другими псевдоэлементами. Адаптив лучше тоже делать так же, посмотри как у меня адаптив работает на брейкпоинтах и пропсе xs={{...}} в компоненте Nav.
3. Файловую структуру тоже сделай как у меня, только твой компонент Error должен лежать по такому шаблону: src/Pages/Error/Error.jsx
4. Пересмотри свой код и вынеси некоторые блоки в отдельные компоненты, как это сделано по структуре у меня, тяжеловато читать файл с 200+ строк кода
5. Пересмотри свои файлы снизу, там тоже есть замечания

2022-08-15 19:56 UTC, AntonSadovnik commented on client/src/components/Error/Error.jsx
> +                >
такие элементы лучше делать кнопками

2022-08-15 19:56 UTC, AntonSadovnik commented on client/src/components/Error/Error.jsx
> +            xs={12} sm={12} md={12} lg={12} xl={12}
если у тебя все сетка на всех брейкпоинтах одинаковая, то можно сделать xs={12} либо вообще их убрать и блок займёт всё возможное пространство, у тебя много такого внизу дальше, исправь везде где дублируешь значения

2022-08-15 19:56 UTC, AntonSadovnik commented on client/src/components/Error/Error.jsx
> +                    Unfortunately, there is no such page.
просто запиши ERROR 404. PAGE NOT FOUND. Иначе просто тяжело понять что за ошибка произошла

2022-08-15 19:56 UTC, AntonSadovnik commented on client/src/components/product_card/ProductCard.jsx
> +                            WANT!
лучше кнопкой сделать

2022-08-15 19:56 UTC, AntonSadovnik commented on client/src/components/product_card/ProductCard.jsx
> +                    xs={12} sm={12} md={7} lg={7} xl={7}
здесь можно сделать так: xs={12} md={7}

2022-08-18 14:34 UTC, LarisaDoroshchuk commented on client/src/components/Error/Error.jsx
> +            xs={12} sm={12} md={12} lg={12} xl={12}
Изменила.

2022-08-18 14:34 UTC, LarisaDoroshchuk commented on client/src/components/Error/Error.jsx
> +                    Unfortunately, there is no such page.
Изменила

2022-08-18 14:36 UTC, LarisaDoroshchuk commented on client/src/components/Error/Error.jsx
> +                >
Я считаю более правильно пока оставить данную реализацию.

2022-08-18 14:37 UTC, LarisaDoroshchuk commented on client/src/components/product_card/ProductCard.jsx
> +                            WANT!
Я считаю более правильно пока оставить данную реализацию.

2022-08-18 14:39 UTC, LarisaDoroshchuk commented on client/src/components/product_card/ProductCard.jsx
> +                    xs={12} sm={12} md={7} lg={7} xl={7}
Изменила

2022-08-18 14:51 UTC, LarisaDoroshchuk commented
> 1. Все иконки, которые вы загружаете, лучше сделать иконками через материал, у меня в файле json есть зависимость, просто установите себе на локалку и загрузите значки пользовательского интерфейса, если вам нужен пример, как с ними работать, смотри документ и мой компонент Activity.jsx, что в заголовке находится
....................
?!?
Расскажешь на митинге подробности.

> 2. Попробуй стили записывать инлайново в сам компонент, если они не повторяются несколько к ряду или это не ховеры с псевдодругими классами. Адаптив лучше тоже делать так же, посмотри как у меня реагируют на брейкпоинты и пропсе xs={{...}} в компоненте Nav.
..........
Мы договорились на общем собрании, что пишем стили в модулях scss. Согласно этому я перенесла все стили с самих компонентов. 

> 3. Файловую структуру тоже сделай как у меня, только твой компонент Error должен лежать по такому шаблону: src/Pages/Error/Error.jsx
...................
Не вижу разницы между нашими структурами...

> 4. Пересмотри свой код и вынеси блоки в определенных компонентах, как это сделано по ограничению у меня, тяжеловато читать файл с 200+ строк кода
........................
Это единый компонент,  не вижу смысла размазывать логику.
И 200 строк кода, это не очень много, как по мне...


> 5. Там тоже есть замечания
....................
+

2022-08-20 10:45 UTC, AntonSadovnik approved these changes

2022-08-20 10:46 UTC, merged