bug fixes after review
AntonSadovnik/final-project-shop pull request #19
Opened 2022-08-22 20:06 UTC by GRuslann

2022-08-22 20:53 UTC, AntonSadovnik requested changes
1. Замечания внизу
2. Лучше выносить стили в пропсу sx, а scss использовать для стилизации того, что нельзя сделать через material ui: псевдоклассы, элементы что много раз повторяются подряд

2022-08-22 20:53 UTC, AntonSadovnik commented on client/src/Slider/Slider.jsx
> +import CardActions from '@mui/material/CardActions';
однотипные импорты

2022-08-22 20:53 UTC, AntonSadovnik commented on client/src/App.jsx
> +function App() {
зачем две функции App?

2022-08-22 20:53 UTC, AntonSadovnik commented on client/src/Slider/Slider.jsx
> +          <Typography gutterBottom variant="h6" component="div" className='title' sx={{ fontSize: 22,
Typography нужно давать тег p, а не div, посмотри чтобы везде так было

2022-08-23 12:02 UTC, GRuslann commented on client/src/Slider/Slider.jsx
> +import CardActions from '@mui/material/CardActions';
вот здесь что-то сломалось, потому что Slider делал Дима, а у меня он оказался в pull request '-'
Мне наверно лучше его удалить и ещё перезалить?

2022-08-23 12:04 UTC, GRuslann commented on client/src/Slider/Slider.jsx
> +          <Typography gutterBottom variant="h6" component="div" className='title' sx={{ fontSize: 22,
Опять же таки, возможно что-то не так замерджил (

2022-08-24 20:00 UTC, closed without merging