create mui theme
AntonSadovnik/final-project-shop pull request #3
Opened 2022-08-07 18:46 UTC by KShkurina

2022-08-08 18:25 UTC, svrostislav requested changes

2022-08-08 18:25 UTC, svrostislav commented on client/src/Styles/Theme.js
> +            main: colors.primaryButton
test

2022-08-08 20:26 UTC, AntonSadovnik requested changes
Тебе надо обновить свою create mui theme ветку последними изменениями из дева

2022-08-09 07:38 UTC, KShkurina commented
Спулила, смерджила конфликтов не было, запушила, как я поняла этот пулреквест остается.

2022-08-09 07:44 UTC, AntonSadovnik approved these changes

2022-08-09 12:38 UTC, merged