Client data form
AntonSadovnik/final-project-shop pull request #7
Opened 2022-08-12 12:56 UTC by ahruts

Client data form created

2022-08-15 20:11 UTC, AntonSadovnik requested changes
1. Комментарий забыла убрать, ниже пометил где
2. У тебя ClientDataForm.jsx получился большим достаточно, посмотри не можешь ли ты какие то элементы разбить на отдельные компоненты, структуру файлов сделай как у меня
3. Стили, если они не повторяются несколько раз подряд или это не псевдоклассы, лучше записывать конкретно пропсой в компонент, точно так же как и адаптив, для примера можешь посмотреть как я сделал компонент Nav

2022-08-15 20:11 UTC, AntonSadovnik commented on client/src/components/ClientDataForm/ClientDataForm.jsx
> +			// .min(8, 'phone should be of minimum 10 characters length')
коммент оставила?

2022-08-18 18:16 UTC, ahruts commented on client/src/components/ClientDataForm/ClientDataForm.jsx
> +			// .min(8, 'phone should be of minimum 10 characters length')
це не комент, це валідація, яку можливо потім введу, хай буде
Поки не можу розбити, виходять проблеми з валідацією, ще поговорю з Ростіком, але поки так буде
По стилям мене все влаштовує, я винесла в scss те що треба адаптувати, легше все там зберігати. Але я передивлюсь, деякі дійсно можна винести в пропсу

2022-08-19 09:33 UTC, AntonSadovnik commented on client/src/components/ClientDataForm/ClientDataForm.jsx
> +			// .min(8, 'phone should be of minimum 10 characters length')
Адаптив тоже можно в пропсу xs вынести: ты и меньше кода напишешь и в плане код стайла будет всё лучше, поэтому посмотри как оно делается

2022-08-20 10:55 UTC, AntonSadovnik approved these changes

2022-08-20 10:55 UTC, merged